import { Inter } from "next/font/google";
import "./globals.css";
import Nav from "@/components/Nav/Nav";
import Footer from "@/components/Footer/Footer";
import { EventProvider } from '../components/EventContext';

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "proEvelate.in",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <EventProvider>
          <Nav />
          {children}
          <Footer />
        </EventProvider>
      </body>
    </html>
  );
}
