import { Inter } from "next/font/google";
import "./globals.css";
import Nav from "@/components/Nav/Nav";
import Footer from "@/components/Footer/Footer";
import { EventProvider } from '../components/EventContext';
import AOSInitializer from '@/components/AOSInitializer';

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "proEvelate.in",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="stylesheet" href="https://unpkg.com/aos@next/dist/aos.css" />
        <link rel="icon" type="image" href="./logo.png" />
      </head>
      <body className={`${inter.className} dark:bg-slate-900`}>
        <EventProvider>
          <Nav />
          {children}
          <Footer />
        </EventProvider>

        <AOSInitializer />
      </body>
    </html>
  );
}
