import { Inter } from "next/font/google";
import "./globals.css";
import Nav from "@/components/Nav/Nav";
import Footer from "@/components/Footer/Footer";
import { EventProvider } from '../components/EventContext';

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "proEvelate.in",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
      <link rel="stylesheet" href="https://unpkg.com/aos@next/dist/aos.css" />

      </head>
      <body className={`${inter.className} dark:bg-slate-900`}>
        <EventProvider>
          <Nav />
          {children}
          <Footer />
        </EventProvider>

        <script src="https://unpkg.com/aos@next/dist/aos.js"></script>
     <script>
    AOS.init();
  </script>
      </body>
    </html>
  );
}
